// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3AQPfFLXHB2PkFJW9xzBytdrJy2esy4',
    appId: '1:90817750920:web:df0ce3a368899789dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    authDomain: 'tripify-first.firebaseapp.com',
    storageBucket: 'tripify-first.appspot.com',
    measurementId: 'G-CKN3ZW9PFX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRKU3On_YiZ7b4t3VGJq4zgbXZ2Uxa8A',
    appId: '1:90817750920:ios:0f10d7047e36cdd7dd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    storageBucket: 'tripify-first.appspot.com',
    iosClientId: '90817750920-hh4afd2l14apsabtrgvm1si7luud2e6i.apps.googleusercontent.com',
    iosBundleId: 'com.tripify.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRKU3On_YiZ7b4t3VGJq4zgbXZ2Uxa8A',
    appId: '1:90817750920:ios:3d4a1b8b26f28b3ddd7c3d',
    messagingSenderId: '90817750920',
    projectId: 'tripify-first',
    storageBucket: 'tripify-first.appspot.com',
    iosClientId: '90817750920-fjnc0lhbluq45fkm8g3igutfqjosh3kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
